# Generated by Django 5.0.6 on 2024-07-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
