# Generated by Django 5.0.6 on 2024-07-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_pedidos_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
