# Generated by Django 5.0.6 on 2024-07-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_remove_pedidos_numero_pedidos_enproceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador',
            name='desarrollo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
